[package]
name = "log-layer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0"
log="0.4.17"
log4rs="1.2.0"

[build-dependencies]
cxx-build = "1.0"

[lib]
crate-type = ["staticlib"]
